[workspace]
authors = ["Agustin Corbat <agustin.corbat@gmail.com>"]
channels = ["conda-forge"]
name = "cv_migrator"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
migrate = "powershell -Command 'Get-ChildItem -Path ./CV_A_corbat/main*.tex | ForEach-Object { python old_text_to_yaml.py $_.FullName }'"

[dependencies]
python = ">=3.13.2,<3.14"
pyyaml = ">=6.0.2,<7"
